{
 "title": "Mesh Fiber",
 "description": "Dashboard for applications that use https://github.com/ansrivas/fiberprometheus",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(pocketcore_geo_mesh_requests_total, namespace)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(pocketcore_geo_mesh_requests_total, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(pocketcore_geo_mesh_requests_total, instance)"
    }
   },
   {
    "name": "handler",
    "label": "Handler",
    "query": {
     "query": "label_values(pocketcore_geo_mesh_requests_total, path)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Traffic - Req/s",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(pocketcore_geo_mesh_requests_total{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[2m])) by (job)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Traffic by instance - Req/s",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(pocketcore_geo_mesh_requests_total{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[2m])) by (job, instance)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }} - {{ instance }}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Traffic - Req/s by handler",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(pocketcore_geo_mesh_requests_total{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[2m])) by (job, method, path)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }} - {{ method }} {{handler}}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Errors - % (5xx)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(pocketcore_geo_mesh_requests_total{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\", status=\"500|502|503|504\"}[5m])) by (job)/sum(rate(pocketcore_geo_mesh_requests_total{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[5m])) by (job)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }} - {{ method }} {{handler}}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Errors - % by handler (5xx)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(pocketcore_geo_mesh_requests_total{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\", status=\"500|502|503|504\"}[5m])) by (job, method, handler)/sum(rate(pocketcore_geo_mesh_requests_total{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[5m])) by (job, method, handler)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }} - {{ method }} {{handler}}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latency - General",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "histogram_quantile(0.5, sum by (job, le) (rate(pocketcore_geo_mesh_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[5m])))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }} - p50",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "histogram_quantile(0.95, sum by (job, le) (rate(http_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[5m])))",
     "legendFormat": "{{ job }} - p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(http_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[5m])))",
     "legendFormat": "{{ job }} - p99"
    }
   ]
  },
  {
   "title": "Latency by handler",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "histogram_quantile(0.5, sum by (job, method, handler, le) (rate(pocketcore_geo_mesh_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[5m])))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }} - {{ method }} {{ handler }} - p50",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "histogram_quantile(0.95, sum by (job, method, handler, le) (rate(http_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[5m])))",
     "legendFormat": "{{ job }} - {{ method }} {{ handler }} - p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, method, handler, le) (rate(http_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[5m])))",
     "legendFormat": "{{ job }} - {{ method }} {{ handler }} - p99"
    }
   ]
  },
  {
   "title": "Latency by instance",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "histogram_quantile(0.5, sum by (job, instance, le) (rate(pocketcore_geo_mesh_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[5m])))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }} - {{ instance }} - p50",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "histogram_quantile(0.95, sum by (job, instance, le) (rate(http_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[5m])))",
     "legendFormat": "{{ job }} - {{ instance }} - p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, instance, le) (rate(http_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[5m])))",
     "legendFormat": "{{ job }} - {{ instance }} - p99"
    }
   ]
  },
  {
   "title": "Latency 99p by instance",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (job, instance, le) (rate(pocketcore_geo_mesh_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[5m])))",
     "legendFormat": "{{ job }} - {{ instance }} - p99"
    }
   ]
  }
 ]
}